- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.Xresources:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.shell:
    ~/.gitconfig:
    ~/.i3:
    ~/.inputrc:
    ~/.taskrc:
    ~/.tmux.conf:
    ~/.uncrustify.cfg:
    ~/.vim:
    ~/.vimrc:
    ~/.xinitrc:
    ~/bin:

    ~/.config/termite/config: termite.conf
    ~/.config/Code/User: vscode
    ~/.config/dunst/dunstrc: dunstrc.conf
    ~/.config/ranger/colorschemes: ranger/colorschemes
    ~/.config/ranger/rc.conf: ranger/rc.conf
    ~/.config/ranger/rifle.conf: ranger/rifle.conf
    ~/.config/ranger/scope.sh: ranger/scope.sh
    ~/.config/redshift.conf: redshift.conf
