- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitconfig:
    ~/.inputrc:
    ~/.shell:
    ~/.taskrc:
    ~/.tmux.conf:
    ~/.uncrustify.cfg:
    ~/.vim:
    ~/.vimrc:
    ~/bin:

    "~/Library/Application Support/Code/User": vscode
    ~/.config/nvim: neovim
    ~/.config/ranger/rc.conf: ranger/rc.conf
    ~/.config/ranger/rifle.conf: ranger/rifle.conf
    ~/.config/ranger/scope.sh: ranger/scope.sh
