- pacaur: &common
    ? asciinema
    ? atool
    ? coreutils
    ? ctop
    ? diff-so-fancy
    ? docker
    ? docker-compose
    ? git
    ? git-extras
    ? go
    ? htop
    ? jq
    ? lastpass-cli
    ? ngrok
    ? perl
    ? php
    ? rsync
    ? shellcheck
    ? subversion
    ? task
    ? tmux
    ? tree
    ? uncrustify
    ? vim
    ? wget
    ? yarn

- pacaur:
    ? compton
    ? cower
    ? deluge
    ? dmenu2
    ? dropbox
    ? dunst
    ? exercism-cli
    ? feh
    ? firefox
    ? gifsicle
    ? go-tools
    ? google-chrome-dev
    ? gscreenshot
    ? hub-git
    ? i3
    ? imagemagick
    ? inkscape
    ? kid3
    ? krita
    ? libreoffice-fresh
    ? meld
    ? network-manager-applet
    ? networkmanager
    ? nodejs
    ? noto-fonts
    ? noto-fonts-emoji
    ? numlockx
    ? nvim
    ? openssh
    ? pacaur
    ? playerctl
    ? plex-media-server
    ? postman-bin
    ? pulseaudio
    ? pulseaudio-alsa
    ? pulseaudio-bluetooth
    ? ranger-git
    ? redshift
    ? reflector
    ? rofi
    ? rustup
    ? sed
    ? simplescreenrecorder
    ? slack-desktop
    ? solaar
    ? spotify
    ? stack
    ? sysstat
    ? termite
    ? ttf-dejavu
    ? ttf-font-awesome
    ? ttf-liberation
    ? ttf-mac-fonts
    ? ttf-monaco
    ? ttf-ms-fonts
    ? udiskie
    ? visual-studio-code
    ? vlc
    ? vlc-pause-click-plugin
    ? w3m
    ? xclip
    ? xorg-apps
    ? zathura
    ? zathura-pdf-poppler
    ? zeal

- brew:
    <<: *common
    ? bash
    ? bash-completion
    ? docker-machine
    ? hub
    ? node
    ? python
    ? python3
    ? ranger
    ? reattach-to-user-namespace
    ? torus
