- pacaur:
    - asciinema
    - compton
    - coreutils
    - cower
    - ctop
    - deluge
    - diff-so-fancy
    - dmenu2
    - docker
    - docker-compose
    - dropbox
    - dunst
    - evince
    - feh
    - firefox
    - gawk
    - gifsicle
    - git
    - git-extras
    - go
    - go-tools
    - google-chrome-dev
    - gscreenshot
    - htop
    - hub-git
    - i3
    - imagemagick
    - inkscape
    - jq
    - kid3
    - krita
    - lastpass-cli
    - less
    - libreoffice-fresh
    - meld
    - network-manager-applet
    - networkmanager
    - ngrok
    - nodejs
    - noto-fonts
    - noto-fonts-emoji
    - numlockx
    - openssh
    - pacaur
    - perl
    - php
    - playerctl
    - plex-media-server
    - postman-bin
    - pulseaudio
    - pulseaudio-alsa
    - pulseaudio-bluetooth
    - ranger-git
    - redshift
    - reflector
    - rofi
    - rsync
    - rustup
    - rxvt-unicode-pixbuf
    - sed
    - shellcheck
    - simplescreenrecorder
    - slack-desktop
    - solaar
    - spotify
    - subversion
    - sysstat
    - task
    - tmux
    - tree
    - ttf-dejavu
    - ttf-font-awesome
    - ttf-liberation
    - ttf-mac-fonts
    - ttf-monaco
    - ttf-ms-fonts
    - udiskie
    - uncrustify
    - urxvt-clipboard
    - urxvt-vtwheel
    - vim
    - visual-studio-code
    - vlc
    - vlc-pause-click-plugin
    - w3m
    - wget
    - xclip
    - yarn
    - zeal

- brew:
    - asciinema
    - bash
    - bash-completion
    - ctop
    - docker
    - docker-compose
    - docker-machine
    - git
    - git-extras
    - go
    - grep
    - htop
    - hub
    - jq
    - lastpass-cli
    - node
    - python
    - python3
    - ranger
    - rsync
    - shellcheck
    - subversion
    - task
    - tmux
    - torus
    - tree
    - uncrustify
    - vim
    - wget
    - yarn

