#!/usr/bin/env bash
# shellcheck disable=SC1090
set -e

command -v python > /dev/null || { echo "Python must be installed first."; exit 1; }
[[ $USER == 'root' ]] && { echo "Don't run this as root."; exit 1; }

dotfiles="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )"
dotbot="$dotfiles/dotbot/bin/dotbot"
dotbot_plugins="$dotfiles/.lib/plugins"
config_dir="$dotfiles/.lib/config"
configs=(
    "$config_dir/config.yml"
    "$config_dir/config.$(uname).yml"
)

args=()
while test $# -gt 0; do
    case "$1" in
        --packages)
            configs+=(
                "$config_dir/packages.$(uname).yml"
            )
            shift
            ;;
        *)
            args+=( "$1" )
            shift
            ;;
    esac
done

# TODO: Move into a dotbot "shell" field
# Update bash-completions
. "$dotfiles/shell/completions/.sources.sh"

config_file="$(mktemp --suffix=.yml)"
cat "${configs[@]}" > "$config_file"

git submodule update --remote --merge
"$dotbot" -d "$dotfiles" -c "$config_file" --plugin-dir "$dotbot_plugins" "${args[@]}"

rm "$config_file"
