#!/usr/bin/env bash
# shellcheck disable=SC1090

[[ ! -f /usr/bin/python ]] && echo "Python must be installed first." && exit 1
[[ $EUID == 0 || $HOME == '/root' ]] && echo "Don't run this as root." && exit 1

config="install.conf.$(uname -n).yml"
dotbot_dir="dotbot"
dotbot_bin="bin/dotbot"
basedir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Make $HOME/bin if it doesn't exist
mkdir -p "$HOME"/bin

# Update bash-completions
. "$basedir/bash-completions/.sources.sh"

set -e

cd "$basedir"
git submodule update --remote --merge

"${basedir}/${dotbot_dir}/${dotbot_bin}" -d "${basedir}" -c "${config}" "${@}"
