#!/usr/bin/env python3.7
"""Postinstall hook for syncing global npm packages."""
from _shared import get_toplevel_packages, write_pkg_file


def main() -> None:
    """Main entrypoint."""
    if get_toplevel_packages() is not None:
        write_pkg_file()


if __name__ == "__main__":
    main()
