#!/usr/bin/env bash
#
# Displays battery level
#
declare -i battery_level
declare -u battery_status
declare time_remaining

battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)
time_remaining=$(acpi | sed 's/.*, \([0-9]\{2\}:[0-9]\{2\}\).*/\1/')

# Full text
echo "BAT ${battery_level}% ${battery_status:0:3} (${time_remaining})"
# Short text
echo "BAT ${battery_level}% ${battery_status:0:1}"

# Text color
if [[ $battery_status = Discharging ]]; then
    if ((battery_level < 20)); then
        echo '#FF5555'
    elif ((battery_level < 50)); then
        echo '#F1FA8C'
    fi
fi
