#!/usr/bin/env bash

declare -i count
count=$(trash-list | wc -l)

if ((BLOCK_BUTTON == 2)); then
    i3-nagbar -t warning --font 'pango:Monaco' -m 'Empty the trash?' -B 'Empty' 'trash-empty && killall i3-nagbar && i3-msg restart' &> /dev/null
fi

if ((count > 0)); then
    echo "$count"
    echo "$count"
fi

if ((count >= 50)); then
    xrdb -query | awk '/red/{ print $2 }'
fi

