tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
tap "manifoldco/brew"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Portable Foreign Function Interface library
brew "libffi"
# Low-level library for pixel manipulation
brew "pixman"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c"
# Icons for the GNOME project
brew "adwaita-icon-theme"
# Apache Portable Runtime library
brew "apr"
# SSL/TLS cryptography library
brew "openssl"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# General-purpose data compression with high compression ratio
brew "xz"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Record and share terminal sessions
brew "asciinema"
# Automatic configure script builder
brew "autoconf"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.1+
brew "bash-completion@2"
# Collection of portable C++ source libraries
brew "boost"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Top-like interface for container metrics
brew "ctop"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Create Docker hosts locally and on cloud providers
brew "docker-machine", restart_service: true, link: false
# YAML Parser
brew "libyaml"
# Interpreted, interactive, object-oriented programming language
brew "python@2"
# Isolated development environments using Docker
brew "docker-compose"
# Command-line tool to interact with exercism.io
brew "exercism"
# Collection of GNU find, xargs, and locate
brew "findutils", args: ["with-default-names"]
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU awk utility
brew "gawk"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# GNU implementation of the famous stream editor
brew "gnu-sed", args: ["with-default-names"]
# ASN.1 structure parser library
brew "libtasn1"
# C string library for manipulating Unicode strings
brew "libunistring"
# Low-level cryptographic library
brew "nettle"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU grep, egrep and fgrep
brew "grep", args: ["with-default-names"]
# Toolkit for creating graphical user interfaces
brew "gtk+3"
# Text view with syntax, undo/redo, and text marks
brew "gtksourceview3"
# The Haskell Tool Stack
brew "haskell-stack", link: false
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Add GitHub support to git on the command-line
brew "hub"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# LastPass command-line interface tool
brew "lastpass-cli"
# Asynchronous event library
brew "libevent"
# GNOME XML library
brew "libxml2"
# Utility for directing compilation
brew "make", args: ["with-default-names"]
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Utility for managing network connections
brew "netcat"
# Platform built on V8 to build network applications
brew "node"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Shell command parallelization utility
brew "parallel"
# General-purpose scripting language
brew "php"
# Tool to automatically fix PHP coding standards issues
brew "php-cs-fixer"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Show ps output as a tree
brew "pstree"
# Python 2 bindings for the Cairo graphics library
brew "py2cairo"
# GNOME Python bindings (based on GObject Introspection)
brew "pygobject3"
# File browser
brew "ranger"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Database of common MIME types
brew "shared-mime-info"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Version control system designed to be a better CVS
brew "subversion"
# Feature-rich console based todo list manager
brew "task"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Source code beautifier
brew "uncrustify"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
cask "alfred"
cask "bartender"
cask "dash"
cask "dropbox"
cask "firefoxdeveloperedition"
cask "flux"
cask "haskell-platform"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "ngrok"
cask "postman"
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "sketch"
cask "sketchpacks"
cask "slack"
cask "spotify"
cask "transmission"
cask "visual-studio-code"
cask "vmware-horizon-client"
cask "windscribe"
cask "caskroom/versions/atom-beta"
cask "caskroom/versions/google-chrome-canary"
mas "Amphetamine", id: 937984704
mas "Gapplin", id: 768053424
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Trello", id: 1278508951
mas "Typeeto", id: 970502923
mas "Xcode", id: 497799835
