- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- shell:
    - description: Updating Dotbot Plugins
      command: ~/.dotfiles/.lib/shell/update-plugins.sh
      stdout: true
    - description: Synchronizing secure files
      command: ~/.dotfiles/.lib/shell/lpass.sh
    - description: Updating bash completions
      command: ~/.dotfiles/.lib/shell/update-completions.sh
      stdout: true

- link:
    # Directories
    ~/.vim:
    ~/bin:
    $XDG_DATA_HOME/task/hooks: config/task/hooks

    # Files
    ~/.gitconfig: global.gitconfig
    ~/.vimrc: vim/.vimrc

- merge:
    ~/.config: config
    '~': languages
    '~': shell

