- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- shell:
    - description: Updating Dotbot Plugins
      command: ~/.dotfiles/.lib/shell/update-plugins.sh
      stdout: true
    - description: Synchronizing secure files
      command: ~/.dotfiles/.lib/shell/lpass.sh
    - description: Updating bash completions
      command: ~/.dotfiles/.lib/shell/update-completions.sh
      stdout: true

- link:
    # Directories
    ~/.config/nvim/init.vim: vim/.init.vim
    ~/.config/ranger: ranger
    ~/.shell:
    ~/.vim:
    ~/bin:

    # Files
    ~/.bash_logout: shell/.bash_logout
    ~/.bash_profile: shell/.bash_profile
    ~/.bashrc: shell/.bashrc
    ~/.gitconfig: global.gitconfig
    ~/.inputrc: shell/.inputrc
    ~/.stylish-haskell.yaml: languages/.stylish-haskell.yaml
    ~/.prettierrc.yml: languages/.prettierrc.yml
    ~/.taskrc:
    ~/.tmux.conf:
    ~/.uncrustify.cfg: languages/.uncrustify.cfg
    ~/.vimrc: vim/.vimrc

- merge:
    ~/.config: config

