- defaults:
    link:
      create: true
      relink: true

- clean:
    - $HOME
    - $XDG_CONFIG_HOME
    - ~/.local/lib
    - ~/.local/bin

# %{GENERATED}%

- keybase:
    $XDG_DATA_HOME/task/freecinc.ca.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.ca.pem
    $XDG_DATA_HOME/task/freecinc.cert.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.cert.pem
    $XDG_DATA_HOME/task/freecinc.key.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.key.pem

- merge:
    $XDG_CONFIG_HOME: config
    ~/.local/lib: local/lib
    ~/.local/bin: local/bin

- merge:
    ~/.local/bin: local/lib/bin-patched.d

- link:
    # Core
    ~/.bashrc:
    ~/.bash_logout:
    ~/.bash_profile:

    # Misc
    ~/.ssh/config: config/openssh/config
    $XDG_DATA_HOME/npm/lib/node_modules/.hooks: config/npm/hooks
    $XDG_DATA_HOME/task/hooks: config/task/hooks

# %{OS_SPECIFIC}%

- shell:
    - description: Updating bash completions
      command: ~/.dotfiles/.lib/shell/update-completions
      stdout: true
    - description: Updating phpcs rulesets
      command: ~/.dotfiles/.lib/shell/update-phpcs
      stdout: true
    - description: Updating pipx packages
      command: pipx upgrade-all
      stdout: true
