- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config', '~/.local/bin']

- shell:
    - description: Synchronizing secure files
      command: ~/.dotfiles/.lib/shell/lpass
    - description: Updating bash completions
      command: ~/.dotfiles/.lib/shell/update-completions
      stdout: true
    - description: Updating pipsi packages
      command: ~/.dotfiles/.lib/shell/update-pipsi-packages
      stdout: true

- link:
    # Directories
    ~/.vim:
    $XDG_DATA_HOME/task/hooks: config/task/hooks

    # Files
    ~/.vimrc: vim/.vimrc
    $XDG_CONFIG_HOME/redshift.conf: config/redshift/redshift.conf

- merge:
    '~': languages
    '~': shell
    ~/.config: config
    ~/.local/bin: bin

