- shell:
    - description: Saving Brewfile
      command: brew bundle dump --describe --force --file=~/.dotfiles/.lib/config/generated/Brewfile

- link:
    # Directories
    "~/Library/Application Support/Code/User": vscode
