- defaults:
    link:
      create: true
      relink: true

- clean:
    - $HOME
    - $HOME/.local/bin
    - $XDG_CONFIG_HOME

# %{GENERATED}%

- keybase:
    $XDG_DATA_HOME/task/freecinc.ca.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.ca.pem
    $XDG_DATA_HOME/task/freecinc.cert.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.cert.pem
    $XDG_DATA_HOME/task/freecinc.key.pem:
      /keybase/private/dsifford/taskwarrior/freecinc.key.pem

- merge:
    $HOME: shell
    $HOME/.local/bin: bin
    $XDG_CONFIG_HOME: config

- link:
    # Directories
    $HOME/.vim: vim
    $XDG_DATA_HOME/npm/lib/node_modules/.hooks: config/npm/hooks
    $XDG_DATA_HOME/task/hooks: config/task/hooks

    # Files
    $HOME/.ssh/config: config/ssh/config
    $HOME/.vimrc: vim/.vimrc

# %{OS_SPECIFIC}%

- shell:
    - description: Updating bash completions
      command: ~/.dotfiles/.lib/shell/update-completions
      stdout: true
    - description: Updating pipsi packages
      command: ~/.dotfiles/.lib/shell/update-pipsi-packages
      stdout: true
