
- trizen:
    # Groups
    - base
    - base-devel
    - i3
    - texlive-most
    - xorg

    # Official Packages
    - arandr                     # Provide a simple visual front end for XRandR 1.2.
    - archlinux-wallpaper        # A variety of Arch Linux branded wallpapers
    - asciinema                  # Record and share terminal sessions
    - atool                      # A script for managing file archives of various types
    - aws-cli                    # Universal Command Line Interface for Amazon Web Services
    - bash-completion            # Programmable completion for the bash shell
    - blueman                    # GTK+ Bluetooth Manager
    - bluez-firmware             # Firmwares for Broadcom BCM203x and STLC2300 Bluetooth chips
    - bluez-utils                # Development and debugging utilities for the bluetooth protocol stack
    - deluge                     # A BitTorrent client with multiple user interfaces in a client/server model
    - diff-so-fancy              # Good-looking diffs with diff-highlight and more
    - docker                     # Pack, ship and run any application as a lightweight container
    - docker-compose             # Fast, isolated development environments using Docker
    - docker-machine             # Machine management for a container-centric world
    - dunst                      # Customizable and lightweight notification-daemon
    - fdupes                     # a program for identifying or deleting duplicate files residing within specified directories
    - feh                        # Fast and light imlib2-based image viewer
    - ffmpeg                     # Complete solution to record, convert and stream audio and video
    - ffmpegthumbnailer          # Lightweight video thumbnailer that can be used by file managers.
    - firefox-developer-edition  # Developer Edition of the popular Firefox web browser
    - flake8                     # The modular source code checker: pep8, pyflakes and co
    - gdb                        # The GNU Debugger
    - ghc                        # The Glasgow Haskell Compiler
    - git                        # the fast distributed version control system
    - gnome-keyring              # Stores passwords and encryption keys
    - gnu-netcat                 # GNU rewrite of netcat, the network piping application
    - go                         # Core compiler tools for the Go programming language
    - go-tools                   # Developer tools for the Go programming language
    - gparted                    # A Partition Magic clone, frontend to GNU Parted
    - highlight                  # Fast and flexible source code highlighter (CLI version)
    - htop                       # Interactive process viewer
    - imagemagick                # An image viewing/manipulation program
    - inkscape                   # Professional vector graphics editor
    - jq                         # Command-line JSON processor
    - krita                      # Edit and paint images
    - lastpass-cli               # LastPass command line interface tool
    - libreoffice-fresh          # LibreOffice branch which contains new features and program enhancements
    - linux-headers              # Header files and scripts for building modules for Linux kernel
    - neovim                     # Fork of Vim aiming to improve user experience, plugins, and GUIs
    - networkmanager             # Network connection manager and user applications
    - network-manager-applet     # Applet for managing network connections
    - nmap                       # Utility for network discovery and security auditing
    - nodejs                     # Evented I/O for V8 javascript
    - noto-fonts                 # Google Noto TTF fonts
    - noto-fonts-cjk             # Google Noto CJK fonts
    - noto-fonts-emoji           # Google Noto emoji fonts
    - npm                        # A package manager for javascript
    - ntfs-3g                    # NTFS filesystem driver and utilities
    - numlockx                   # Turns on the numlock key in X11.
    - nvidia                     # NVIDIA drivers for linux
    - nvidia-settings            # Tool for configuring the NVIDIA graphics driver
    - openssh                    # Free version of the SSH connectivity tools
    - openvpn                    # An easy-to-use, robust and highly configurable VPN (Virtual Private Network)
    - p7zip                      # Command-line file archiver with high compression ratio
    - pandoc                     # Conversion between markup formats
    - parallel                   # A shell tool for executing jobs in parallel
    - pavucontrol                # PulseAudio Volume Control
    - php                        # A general-purpose scripting language that is especially suited to web development
    - playerctl                  # mpris media player controller and lib for spotify, vlc, audacious, bmp, xmms2, and others.
    - pulseaudio                 # A featureful, general-purpose sound server
    - pulseaudio-alsa            # ALSA Configuration for PulseAudio
    - pulseaudio-bluetooth       # Bluetooth support for PulseAudio
    - python                     # Next generation of the python high-level scripting language
    - python2                    # A high-level scripting language
    - python2-pip                # The PyPA recommended tool for installing Python packages
    - python-lxml                # Python3 binding for the libxml2 and libxslt libraries
    - python-neovim              # Python 3 client for neovim
    - python-pip                 # The PyPA recommended tool for installing Python packages
    - python-pycodestyle         # Python style guide checker
    - python-pylint              # Analyzes Python code looking for bugs and signs of poor quality
    - python-rope                # Refactoring library
    - python-xdg                 # Python library to access freedesktop.org standards
    - redshift                   # Adjusts the color temperature of your screen according to your surroundings.
    - ripgrep                    # A search tool that combines the usability of ag with the raw speed of grep
    - rsync                      # A file transfer program to keep remote files in sync
    - rustup                     # The Rust toolchain installer
    - shellcheck                 # Shell script analysis tool
    - simplescreenrecorder       # A feature-rich screen recorder that supports X11 and OpenGL.
    - slop                       # Utility to query the user for a selection and print the region to stdout
    - stack                      # The Haskell Tool Stack
    - subversion                 # A Modern Concurrent Version Control System
    - sysstat                    # a collection of performance monitoring tools (iostat,isag,mpstat,pidstat,sadf,sar)
    - task                       # A command-line todo list manager
    - termite                    # A simple VTE-based terminal
    - time                       # Utility for monitoring a program's use of system resources
    - tmux                       # A terminal multiplexer
    - tree                       # A directory listing program displaying a depth indented list of files
    - ttf-dejavu                 # Font family based on the Bitstream Vera Fonts with a wider range of characters
    - ttf-font-awesome           # Iconic font designed for Bootstrap
    - ttf-liberation             # Red Hats Liberation fonts.
    - udiskie                    # Removable disk automounter using udisks
    - uncrustify                 # A source code beautifier
    - unzip                      # For extracting and viewing files in .zip archives
    - vlc                        # Multi-platform MPEG, VCD/DVD, and DivX player
    - w3m                        # Text-based Web browser as well as pager
    - wget                       # Network utility to retrieve files from the Web
    - xclip                      # Command line interface to the X11 clipboard
    - xdotool                    # Command-line X11 automation tool
    - xorg-xinit                 # X.Org initialisation program
    - xterm                      # X Terminal Emulator
    - yapf                       # Python style guide checker
    - yarn                       # Fast, reliable, and secure dependency management
    - zathura                    # Minimalistic document viewer
    - zathura-pdf-poppler        # Adds pdf support to zathura by using the poppler engine
    - zip                        # Compressor/archiver for creating and modifying zipfiles

    # AUR Packages
    - albert                  # A sophisticated standalone keyboard launcher.
    - atom-editor-bin         # Atom is a hackable text editor for the 21st century built on Electron - Precompiled binary from official repository
    - autokey-py3             # Python 3 port of AutoKey, a desktop automation utility for Linux and X11 with new features.
    - ctop                    # Top-like interface for container metrics
    - doctl-bin               # A command line tool for DigitalOcean services
    - dropbox                 # A free service that lets you bring your photos, docs, and videos anywhere and share them easily.
    - exercism-cli            # Command line client for exercism.io
    - git-extras              # GIT utilities -- repo summary, commit counting, repl, changelog population and more
    - google-chrome-dev       # The popular and trusted web browser by Google (Dev Channel)
    - gscreenshot             # A simple screenshot tool supporting multiple backends
    - hub-git                 # cli interface for Github
    - keybase-bin             # the Keybase Go client, filesystem, and GUI
    - ngrok                   # A tunneling, reverse proxy for developing and understanding networked, HTTP services
    - php-codesniffer         # PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files to detect and fix violations of a defined set of coding standards.
    - plex-media-server       # Plex Media Server
    - postman-bin             # Build, test, and document your APIs faster
    - ranger-git              # A simple, vim-like file manager.
    - shfmt                   # Format shell programs
    - solaar                  # Device manager for Logitech's Unifying receiver peripherals
    - spotify                 # A proprietary music streaming service
    - trizen                  # Trizen AUR Package Manager: A lightweight wrapper for AUR.
    - ttf-monaco              # A monospaced sans-serif typeface by Apple Inc.
    - ttf-ms-fonts            # Core TTF Fonts from Microsoft
    - unetbootin              # Create bootable Live USB drives
    - universalindentgui-svn  # A GUI for GNU Indent, Uncrustify, Artistic Styler, PHP Stylist, Ruby Beautify, HTML Tidy and many other
    - visual-studio-code-bin  # Visual Studio Code: Editor for building and debugging modern web and cloud applications (official binary version)
    - windscribe-cli          # Port of Windscribe's VPN command line interface
    - zeal-git                # A simple documentation browser
