if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	[ -x "$f" ] && . "$f"
    done
    unset f
fi


[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

/usr/bin/numlockx on
/home/dsifford/bin/screenlayout
udiskie &

exec i3 -V >> ~/i3log-"$(date +'%F-%k-%M-%S')" 2>&1
