#!/usr/bin/node
const fs = require('fs');
const exec = require('child_process').exec;
const { HOME } = process.env;

const haystack = fs.readFileSync(`${HOME}/.dotfiles/packages.cson`, 'utf8');
const hs = haystack.match(/"(.+)"/g).map(p => p.replace(/"/g, ''));
const needle = fs.readdirSync(`${HOME}/.atom/packages`)
  .filter(p => p !== '.wlck' && haystack.indexOf(p) === -1)
  .join('\n');

console.log(needle);
