#!/usr/bin/python2

import sys
from phue import Bridge

b = Bridge('192.168.1.121', '1bf65ff514536e0e70a846a26cacb459')
b.connect()


if not len(sys.argv) == 0 or sys.argv[1] == 'toggle':
    b.set_light([1, 2], 'on', not b.get_light(1, 'on'))
    sys.exit()

if sys.argv[1] == 'brightness': 
    b.set_light([1, 2], 'bri', (b.get_light(1, 'bri') + int(sys.argv[2])))
    sys.exit()


