#!/bin/bash
[[ $(uname -n) == 'desktop' ]] && \
    xrandr \
        --output DP-4 --primary --mode 3840x2160 --pos 2160x0 --rotate normal \
        --output DP-2.8 --mode 3840x2160 --pos 0x0 --rotate right
