#!/usr/bin/env bash
# shellcheck disable=SC1090
set -e

shopt -s extglob nullglob

[[ $USER == 'root' ]] && {
    echo "Don't run this as root."
    exit 1
}

command -v python3 > /dev/null || {
    echo "python3 must be installed first."
    exit 1
}

command -v dotbot > /dev/null || {
    echo "dotbot must be installed first."
    exit 1
}

DOTFILES="${DOTFILES:-~/.dotfiles}"

config_dir="$DOTFILES"/.lib/config
generated=("$config_dir"/generated/packages.*.yml)
args=()

while test $# -gt 0; do
    case "$1" in
        --packages)
            generated+=("$config_dir"/generated/os.packages."$(uname)".yml)
            shift
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

dotbot \
    --base-directory "$DOTFILES" \
    --plugin-dir "$DOTFILES"/.lib/plugins \
    --config-file <(
        sed --posix -e '/^# %{[A-Z_]*}%.*$/{
            /GENERATED/{
                '"$(for f in "${generated[@]}"; do echo "r $f"; done)"'
                d
            }
            /OS_SPECIFIC/{
                r '"$config_dir/config.$(uname).yml"'
                d
            }
        }' "$config_dir"/config.yml
    ) \
    "${args[@]}"
