#!/bin/sh
# shellcheck disable=SC1090
#

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
fi

xrdb -merge "$XDG_CONFIG_HOME"/X11/Xresources

# System specific files
for f in "$XDG_CONFIG_HOME"/X11/Xresources.d/"$(uname -n)"/*.ad; do
    xrdb -merge "$f"
done
unset f

# Increase key repeat rate
xset r rate 200 60

# Caps Lock => Escape
setxkbmap -option caps:escape

numlockx &
udiskie &

exec i3 --shmlog-size=26214400
