#!/usr/bin/env bash

# skip binaries in $HOME
phpcs=$(type -ap phpcs | grep --invert-match "$HOME" | head -n1)

if [[ -z $phpcs ]]; then
    >&2 echo -bash: phpcs: command not found
    exit 127
fi

$phpcs \
    --colors \
    --runtime-set installed_paths "$XDG_DATA_HOME"/phpcs,"$XDG_DATA_HOME"/phpcs/wpcs \
    --standard=dsifford \
    "$@"
