#!/usr/bin/env bash

# skip binaries in $HOME
svn=$(type -ap svn | sed -n '/\home/!p' | head -n1)

if [[ -z $svn ]]; then
    >&2 echo -bash: svn: command not found
    exit 127
fi

$svn --config-dir "$XDG_CONFIG_HOME"/subversion "$@"
