#!/usr/bin/env bash

# skip binaries in $HOME
wget=$(type -ap wget | grep --invert-match "$HOME" | head -n1)

if [[ -z $wget ]]; then
    >&2 echo -bash: wget: command not found
    exit 127
fi

mkdir -p "$XDG_CACHE_HOME"/wget

$wget --hsts-file="$XDG_CACHE_HOME"/wget/wget-hsts "$@"
