#!/usr/bin/env bash

# skip binaries in $HOME
wget=$(type -aP wget | sed -n '/\home/!p' | head -n1)

if [[ -z $wget ]]; then
    >&2 echo -bash: phpcpf: command not found
    exit 127
fi

mkdir -p "$XDG_CACHE_HOME"/wget

$wget --hsts-file="$XDG_CACHE_HOME"/wget/wget-hsts "$@"
