#!/usr/bin/env python3
# pylint: disable=invalid-name
"""
Daemon script that makes Chrome "Picture-in-picture" windows move to active
window and away from the mouse.
"""
from enum import Enum, auto
from typing import Optional

import i3ipc
from Xlib import display

FLOATING_NAME = "Picture in picture"
FLOATING_MARK = "FLOATING_ACTIVE"
CROSS_MARK = "CROSS"


class Padding(Enum):
    TOP = 270
    RIGHT = 20
    BOTTOM = 20
    LEFT = 20


class Position(Enum):
    TOP = auto()
    RIGHT = auto()
    BOTTOM = auto()
    LEFT = auto()


def has_floating_fullscreen_window(self, workspace) -> bool:
    return next(
        (
            True
            for i in self.get_tree().find_fullscreen()
            if i.floating and i.workspace().name == workspace.name
        ),
        False,
    )


def get_con_output_name(self, con) -> Optional[str]:
    rect = con.props.rect
    return next(
        (
            o.name
            for o in self.get_outputs()
            if (o.rect.x <= rect.x <= o.rect.x + o.rect.width)
            and (o.rect.y <= rect.y <= o.rect.y + o.rect.height)
        ),
        None,
    )


def get_floating_window(self):
    return next(iter(self.get_tree().find_named(FLOATING_NAME)), None)


def get_x_position(output_rect, rect, explicit=None, cross=False) -> int:
    left_value = output_rect.x + Padding.LEFT.value
    right_value = (output_rect.x + output_rect.width) - (
        rect.width + Padding.RIGHT.value
    )
    on_left = output_rect.x + (output_rect.width / 2) > rect.x + (rect.width / 2)
    if explicit is Position.LEFT:
        return left_value
    if explicit is Position.RIGHT:
        return right_value
    if on_left:
        return left_value if not cross else right_value
    return right_value if not cross else left_value


def get_y_position(output_rect, rect, explicit=None) -> int:
    on_top = rect.y + (rect.height / 2) > output_rect.y + (output_rect.height / 2)
    if on_top and explicit is not Position.BOTTOM or explicit is Position.TOP:
        return output_rect.y + Padding.TOP.value
    return output_rect.y + output_rect.height - rect.height - Padding.BOTTOM.value


def mouse_is_hovered(rect) -> bool:
    mouse = display.Display().screen().root.query_pointer()._data
    mouse_x, mouse_y = mouse["root_x"], mouse["root_y"]
    return (rect.x <= mouse_x <= rect.x + rect.width) and (
        rect.y <= mouse_y <= rect.y + rect.height
    )


def translate_window(
    self, container, explicit_x=None, explicit_y=None, cross=False
) -> None:
    current_workspace = self.get_tree().find_focused().workspace().name
    rect = container.props.rect
    output = next(
        (i for i in self.get_outputs() if i.current_workspace == current_workspace),
        None,
    )
    if output is not None:
        container.command(
            (
                "move position"
                f" {get_x_position(output.rect, rect, explicit_x, cross)}"
                f" {get_y_position(output.rect, rect, explicit_y)};"
                " focus tiling"
            )
        )


def on_terminal_fullscreen(self, e) -> None:
    pip_window = get_floating_window(self)
    if (
        e.container.window_instance != "FloatingTerminal"
        or pip_window is None
        or FLOATING_MARK not in pip_window.marks
        or not e.container.fullscreen_mode
    ):
        return
    if get_con_output_name(self, pip_window) == get_con_output_name(self, e.container):
        self.command("focus output left")
        translate_window(self, pip_window)
        self.command("focus output right")


def on_window_focus(self, e) -> None:
    pip_window = get_floating_window(self)
    if (
        pip_window is None
        or FLOATING_MARK not in pip_window.marks
        or pip_window.id != e.container.id
        or not mouse_is_hovered(e.container.props.rect)
    ):
        return
    pip_window.command(f"mark --add --toggle {CROSS_MARK}")
    cross = CROSS_MARK in pip_window.marks
    translate_window(self, pip_window, cross=cross)


i3 = i3ipc.Connection()

i3.on("window::focus", on_window_focus)
i3.on("window::fullscreen_mode", on_terminal_fullscreen)

i3.main()

# vim: set fdn=1:
