#!/usr/bin/env bash

set -e

completions_dir="${XDG_DATA_HOME:?XDG_DATA_HOME must be defined}/bash-completion/completions"
mkdir -p "$completions_dir"

# install generated completions
command -v doctl >/dev/null \
    && doctl completion bash >"$completions_dir"/doctl
command -v npm >/dev/null \
    && npm completion >"$completions_dir"/npm
command -v pandoc >/dev/null \
    && pandoc --bash-completion >"$completions_dir"/pandoc
command -v poetry >/dev/null \
    && poetry completions bash >"$completions_dir"/poetry
command -v rustup >/dev/null \
    && rustup completions bash >"$completions_dir"/rustup

if ! command -v wget >/dev/null; then
    echo '[WARN] wget is not installed. Skipping plugin update...'
    exit 1
fi

declare -A completion_sources=(
    [cargo]='https://raw.githubusercontent.com/rust-lang/cargo/master/src/etc/cargo.bashcomp.sh'
    ['docker-compose']='https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose'
    [docker]='https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker'
    ['docker-machine']='https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash'
    [git]="https://raw.githubusercontent.com/git/git/v$(git --version | awk '{ print $3 }' | head -n 1)/contrib/completion/git-completion.bash"
    ['git-prompt']="https://raw.githubusercontent.com/git/git/v$(git --version | awk '{ print $3 }' | head -n 1)/contrib/completion/git-prompt.sh"
    [hub]='https://raw.githubusercontent.com/github/hub/master/etc/hub.bash_completion.sh'
    [task]='https://raw.githubusercontent.com/GothenburgBitFactory/taskwarrior/master/scripts/bash/task.sh'
    [yarn]='https://raw.githubusercontent.com/dsifford/yarn-completion/master/yarn-completion.bash'
)

parallel --link \
    wget --hsts-file="$XDG_CACHE_HOME/wget-hsts" -q -N -O "$completions_dir"/'{1}' '{2}' \
    ::: "${!completion_sources[@]}" \
    ::: "${completion_sources[@]}"
